Vagrant.configure(2) do |config|
	config.vm.box = "generic/ubuntu2004"
	config.vm.provider "virtualbox" do |vb|
    	vb.gui = false
		vb.memory = "1024"
		vb.disksize.size = '10GB'
	end	
	config.vm.hostname = "Database"
		config.vm.define "db" do |db|
			db.vm.username = "rydraf"
			db.vm.password = "Test@1234"
			db.vm.network "public_network", nat: "Intel(R) Dual Band Wireless-AC 8260"
			db.vm.synced_folder "../vagrant", "/vagrant_data"
			db.vm.provision "shell", inline: <<-SHELL
    		sudo apt update
			sudo apt-get install -y mysql-server
			sudo rm /etc/mysql/mysql.conf.d/mysqld.cnf
			sudo cp /vagrant/mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf
			sudo ufw enable
			sudo ufw allow 3306/tcp
			sudo systemctl restart mysql
			sudo mysql -u root -p
			CREATE USER 'admin'@'192.168.8.200' IDENTIFIED BY 'Test@1234';
			FLUSH PRIVILEGES;
			CREATE DATABASE DEVOPS;
			GRANT ALL PRIVILEGES ON DEVOPS.* TO 'admin'@'192.168.8.200';
			exit
			sudo systemctl restart mysql
			SHELL
		end
	config.vm.hostname = "Webserver"
		config.vm.define "web" do |web|
			web.vm.username = "rydraf"
			web.vm.password = "Test@1234"
			web.vm.network "public_network", nat: "Intel(R) Dual Band Wireless-AC 8260"
			web.vm.synced_folder "../vagrant", "/vagrant_data"
			web.vm.provision "shell", path: "bootstrap.sh"
		end
	end