Vagrant.configure(2) do |config|
	config.vm.box = "generic/centos8"
	config.vm.provider "virtualbox" do |vb|
    vb.gui = false
		vb.memory = "1024"
    #vb.cpu = "1"
  end
  config.vm.synced_folder ".", "/Ansible"
  config.vm.define "wp" do |wp|
    wp.vm.hostname = "wp"
    wp.vm.network  "private_network", ip: "172.20.20.20"
    wp.vm.provision "shell", inline: <<-SHELL
    sudo sed -i "s/.*PasswordAuthentication no.*/PasswordAuthentication yes/" /etc/ssh/sshd_config
    sudo sed -i "s/.*ChallengeResponseAuthentication no.*/ChallengeResponseAuthentication yes/" /etc/ssh/sshd_config
    sudo systemctl restart sshd
    SHELL
  end

  config.vm.define "ctrl" do |ctrl|
    ctrl.vm.hostname = "ctrl"
    ctrl.vm.network  :private_network, ip: "172.20.20.2"
    ctrl.vm.provision "shell", inline: <<-SHELL
      sudo dnf makecache
      sudo dnf install -y ansible git sshpass vim
      sudo cp /Ansible/hosts /etc/ansible/hosts
      sudo sed -i "s/.*#host_key_check.*/host_key_checking = False/" /etc/ansible/ansible.cfg
      sudo sed -i "s/.*PasswordAuthentication no.*/PasswordAuthentication yes/" /etc/ssh/sshd_config
      sudo sed -i "s/.*ChallengeResponseAuthentication no.*/ChallengeResponseAuthentication yes/" /etc/ssh/sshd_config
      sudo systemctl restart sshd
      ansible-galaxy collection install ansible.posix
      
      
      SHELL

  end
end