Vagrant.configure(2) do |config|
	config.vm.box = "generic/ubuntu2004"
	#config.disksize.size = "10GB"
	config.vm.provider "virtualbox" do |vb|
    	vb.gui = false
		vb.memory = "1024"
		#vb.disksize.size = '10GB'
	end	
			config.vm.define "db" do |db|
			#db.ssh.username = "rydraf"
			db.vm.hostname = "Database"
			#db.vm.network "private_network", ip: "172.20.10.100",
				#virtualbox__intnet: true
			db.vm.network "public_network", ip: "192.168.8.100"
			db.vm.synced_folder "../vagrant", "/vagrant"
			db.vm.provision "shell", path: "bootstrap1.sh"
    		
		end
	
		config.vm.define "web" do |web|
			#web.ssh.username = "rydraf"
			web.vm.hostname = "WebServer"
			#web.vm.network "private_network", ip: "172.20.10.200",
			#	virtualbox__intnet: true
			web.vm.network "public_network", ip: "192.168.8.200"
			web.vm.synced_folder "../vagrant", "/vagrant"
			web.vm.provision "shell", path: "bootstrap.sh"
		end
	
	end