---
- hosts: web
  become: true

   
    

  tasks:
    - name: Update apt-get repo and cache
      apt:
       update_cache: yes
       force_apt_get: yes
       cache_valid_time: 3600

    - name: Ensure apache2 is present
      apt:
        name:
          - apache2
          - php
          # - libapache2-mod-php
          # - mysql-client
          # - php-mysql
        state: present

    - name: Allow all access to tcp port 80 and 3306
      ufw:
        rule: allow
        port: '80'
        port: '3306'
        port: '22'
        proto: tcp
        state: enabled

        
- hosts: web1
  become: true
  
  tasks:
    - name: Remove file index.html
      file:
        path: /var/www/html/index.html
        state: absent
        
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /Ansible/index.html
        dest: /var/www/html/index.html


- hosts: web2
  become: true

 
  tasks:
   
    - name: Remove file index.html
      file:
        path: /var/www/html/index.html
        state: absent
        
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /Ansible/html/index.html
        dest: /var/www/html/index.html

