---
- hosts: database
  become: true
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_password: "Test@1234"

  tasks:
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Ensure mysql-server is present
      apt:
        name:
          - mysql-server
          - vim
          - php-mysql
          - python3-pymysql
        state: present

        
    - name: Replace a localhost entry with our own
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: bind-address = 0.0.0.0

  

    - name: Create database user with name 'bob' and password '12345' with all database privileges
      mysql_user:
        name: admin
        password: Test@1234
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock



        

    

    
     