Vagrant.configure(2) do |config|
	config.vm.box = "generic/ubuntu2004"
	config.vm.provider "virtualbox" do |vb|
    vb.gui = false
		vb.memory = "1024"
    #vb.cpu = "1"
  end
  config.vm.synced_folder "../Ansible", "/Ansible"
  config.ssh.password = "vagrant"
  

  config.vm.define "app" do |app|
    app.vm.hostname = "app"
    app.vm.network  "private_network", ip: "172.20.20.111"
    app.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "webapp.yml"
      ansible.verbose = true
    end
  end

  config.vm.define "app2" do |app2|
    app2.vm.hostname = "app2"
    app2.vm.network  "private_network", ip: "172.20.20.112"
  end
	
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network  "private_network", ip: "172.20.20.113"
    db.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "db.yml"
      ansible.verbose = true
    end
  end

  config.vm.define "ctrl" do |ctrl|
    ctrl.vm.hostname = "ctrl"
    ctrl.vm.network  :private_network, ip: "172.20.20.110"
    ctrl.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y ansible git sshpass
      sudo apt-get install -y vagrant vim
      sudo cp /Ansible/hosts /etc/ansible/hosts
      
      SHELL
      #ctrl.vm.provision "ansible_local" do |ansible|
      #ansible.provisioning_path = "Vagrant/Ansible"
      #ansible.inventory_path = "Vagrant/Ansible/hosts"
      #ansible.limit = :all
      #ansible.playbook = "workstation.yml" 
    
  end
end