---
- hosts: app
  become: true

   
    

  tasks:
    - name: Update apt-get repo and cache
      apt:
       update_cache: yes
       force_apt_get: yes
       cache_valid_time: 3600

    - name: Ensure apache2 is present
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - mysql-client
          - php-mysql
        state: present

    - name: Allow all access to tcp port 80
       community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /Ansible/files/index.php
        dest: /var/www/html/index.php
        owner: root
        group: root
        mode: '0644'